#compose.traefik.yml
services:
  marketplace:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME:-marketplace}.rule=Host(`${NAME:-marketplace}.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.${NAME:-marketplace}.entrypoints=websecure"
      - "traefik.http.routers.${NAME:-marketplace}.tls=true"
      - "traefik.http.routers.${NAME:-marketplace}.tls.certresolver=le"
    networks:
      - traefik

networks:
  traefik:
    external: true